// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOperator = "operator"

// Operator mapped from table <operator>
type Operator struct {
	ID             string `gorm:"column:id;primaryKey" json:"id"`
	Name           string `gorm:"column:name;not null" json:"name"`
	OrganizationID string `gorm:"column:organization_id;not null" json:"organization_id"`
}

// TableName Operator's table name
func (*Operator) TableName() string {
	return TableNameOperator
}
