// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameOrganization = "organization"

// Organization mapped from table <organization>
type Organization struct {
	ID     string `gorm:"column:id;primaryKey" json:"id"`
	Name   string `gorm:"column:name;not null" json:"name"`
	APIKey string `gorm:"column:api_key;not null" json:"api_key"`
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
