// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRun = "run"

// Run mapped from table <run>
type Run struct {
	ID        string `gorm:"column:id;primaryKey" json:"id"`
	Name      string `gorm:"column:name;not null" json:"name"`
	StartTime int64  `gorm:"column:start_time;not null" json:"start_time"`
	EndTime   int64  `gorm:"column:end_time;not null" json:"end_time"`
	SessionID string `gorm:"column:session_id" json:"session_id"`
	ThingID   string `gorm:"column:thing_id;not null" json:"thing_id"`
}

// TableName Run's table name
func (*Run) TableName() string {
	return TableNameRun
}
