// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRunComment = "run_comment"

// RunComment mapped from table <run_comment>
type RunComment struct {
	ID         string `gorm:"column:id;primaryKey" json:"id"`
	RunID      string `gorm:"column:run_id;not null" json:"run_id"`
	UserID     string `gorm:"column:user_id;not null" json:"user_id"`
	LastUpdate int64  `gorm:"column:last_update;not null" json:"last_update"`
	Content    string `gorm:"column:content" json:"content"`
}

// TableName RunComment's table name
func (*RunComment) TableName() string {
	return TableNameRunComment
}
