// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSensor = "sensor"

// Sensor mapped from table <sensor>
type Sensor struct {
	ID                   string  `gorm:"column:id;primaryKey" json:"id"`
	SmallID              int32   `gorm:"column:small_id;not null" json:"small_id"`
	Type                 string  `gorm:"column:type;not null" json:"type"`
	LastUpdate           int64   `gorm:"column:last_update;not null" json:"last_update"`
	Category             string  `gorm:"column:category" json:"category"`
	Name                 string  `gorm:"column:name;not null" json:"name"`
	Frequency            int32   `gorm:"column:frequency;not null" json:"frequency"`
	Unit                 string  `gorm:"column:unit" json:"unit"`
	CanID                int64   `gorm:"column:can_id;not null" json:"can_id"`
	Disabled             bool    `gorm:"column:disabled" json:"disabled"`
	ThingID              string  `gorm:"column:thing_id;not null" json:"thing_id"`
	UpperCalibration     float64 `gorm:"column:upper_calibration" json:"upper_calibration"`
	LowerCalibration     float64 `gorm:"column:lower_calibration" json:"lower_calibration"`
	ConversionMultiplier float64 `gorm:"column:conversion_multiplier" json:"conversion_multiplier"`
	UpperWarning         float64 `gorm:"column:upper_warning" json:"upper_warning"`
	LowerWarning         float64 `gorm:"column:lower_warning" json:"lower_warning"`
	UpperDanger          float64 `gorm:"column:upper_danger" json:"upper_danger"`
	LowerDanger          float64 `gorm:"column:lower_danger" json:"lower_danger"`
	UpperBound           float64 `gorm:"column:upper_bound" json:"upper_bound"`
	LowerBound           float64 `gorm:"column:lower_bound" json:"lower_bound"`
	Significance         float64 `gorm:"column:significance" json:"significance"`
}

// TableName Sensor's table name
func (*Sensor) TableName() string {
	return TableNameSensor
}
