// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSession = "session"

// Session mapped from table <session>
type Session struct {
	ID          string `gorm:"column:id;primaryKey" json:"id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description" json:"description"`
	StartDate   int64  `gorm:"column:start_date;not null" json:"start_date"`
	EndDate     int64  `gorm:"column:end_date;not null" json:"end_date"`
	ThingID     string `gorm:"column:thing_id;not null" json:"thing_id"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
