// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSessionComment = "session_comment"

// SessionComment mapped from table <session_comment>
type SessionComment struct {
	ID         string `gorm:"column:id;primaryKey" json:"id"`
	SessionID  string `gorm:"column:session_id;not null" json:"session_id"`
	UserID     string `gorm:"column:user_id;not null" json:"user_id"`
	LastUpdate int64  `gorm:"column:last_update;not null" json:"last_update"`
	Content    string `gorm:"column:content" json:"content"`
}

// TableName SessionComment's table name
func (*SessionComment) TableName() string {
	return TableNameSessionComment
}
