// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameThing = "thing"

// Thing mapped from table <thing>
type Thing struct {
	ID             string `gorm:"column:id;primaryKey" json:"id"`
	Name           string `gorm:"column:name;not null" json:"name"`
	OrganizationID string `gorm:"column:organization_id;not null" json:"organization_id"`
}

// TableName Thing's table name
func (*Thing) TableName() string {
	return TableNameThing
}
