// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameThingOperator = "thing_operator"

// ThingOperator mapped from table <thing_operator>
type ThingOperator struct {
	ID         string `gorm:"column:id;primaryKey" json:"id"`
	OperatorID string `gorm:"column:operator_id;not null" json:"operator_id"`
	ThingID    string `gorm:"column:thing_id;not null" json:"thing_id"`
}

// TableName ThingOperator's table name
func (*ThingOperator) TableName() string {
	return TableNameThingOperator
}
