// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID             string `gorm:"column:id;primaryKey" json:"id"`
	DisplayName    string `gorm:"column:display_name;not null" json:"display_name"`
	Email          string `gorm:"column:email;not null" json:"email"`
	Password       string `gorm:"column:password;not null" json:"password"`
	OrganizationID string `gorm:"column:organization_id" json:"organization_id"`
	Role           string `gorm:"column:role;not null" json:"role"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
