version: "3"
services:
  srv-database-ms:
    # use dockerfile to build image
    build:
      context: .
    # map the container port to the host
    container_name: srv-database-ms
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # use our code as local volume so watcher can run
    volumes:
      - .:/go/src/github.com/SchulichRacingElectrical/srv-database-ms
    working_dir: /go/src/github.com/SchulichRacingElectrical/srv-database-ms
