name: Deployment on Publication

on:
  release:
    types: [published]
jobs:
  environment:
    name: Environment Config
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        env:
          KEYS: ${{ secrets.DATABASE_ENVIRONMENT }}
        run: |
          touch "$GITHUB_WORKSPACE"/.env
          echo "$KEYS"
          echo "$GITHUB_WORKSPACE"
          echo "$KEYS" >> "$GITHUB_WORKSPACE"/.env

  deploy:
    needs: environment
    name: Docker Container deployment
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          sudo docker kill srv-database-ms || true
          sudo docker-compose build --no-cache --pull
          sudo docker-compose up &
